# Week 1, Day 3 (Introduction to Image Processing in Python)
> Welcome to final day (Week 1) of the McE-51069 course. We will introduce Image Processing techniques that can be utilized in various research problems and share you necessary lectures and assignment notebooks.

- toc: true
- badges: false
- comments: true
- categories: [image_processing, overview]

# Numpy

Numpy is a strong third-party library emphasize on numerical calculation in python.<br>
In short, numpy has a `ndArray` data type, which can process numbers, a large numbers of numbers, more efficiently than `List`.

The codes below are reference from [Numpy Official Doc](https://numpy.org/doc/stable/user/quickstart.html)

## The Basics

### Create Array

There are many ways to create numpy array.<br>
The simplest one : from `List`.
```python
array = np.array(list)
```

Or we could create array with **functions** come with **numpy**.<br>
```python
array = np.arange(start, stop, step)
```
But, with `np.arange`, we could not control the number of element in that array. So:
```python
array = np.linspace(start, stop, num)
```
Or, we could just create array from the fly just describe the shape of array that we want.
```python
zeros = np.zeros(shape_in_tuple)
ones = np.ones(shape_in_tuple)
empty = np.empty(shape_in_tuple)
```

In [1]:
#collapse-hide
import numpy as np

# Let's Create an array
array = np.array([1, 2, 3, 4, 5])

# Print Out the Array
print(array)

array = np.arange(2, 20, 2)
print(array)

#Create with the count of array wanted
array = np.linspace(0, 2, 5)
print(array)

# Initialize array for place holder
array = np.zeros((5,5))
print(array)

array = np.ones((5,5))
print(array)

array = np.empty((5,5))
print(array)

[1 2 3 4 5]
[ 2  4  6  8 10 12 14 16 18]
[0.  0.5 1.  1.5 2. ]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


## Basic Operations

In [49]:
#collapse-hide
# Simple Arithmetic Operations
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])

print("Addition of two array : \t", array_a + array_b)
print("Subtraction of two array : \t", array_a - array_b)
print("Multiplication of two array : \t", array_a * array_b)
print("Division of two array : \t", array_a / array_b)

Addition of two array : 	 [5 7 9]
Subtraction of two array : 	 [-3 -3 -3]
Multiplication of two array : 	 [ 4 10 18]
Division of two array : 	 [0.25 0.4  0.5 ]


In [53]:
#collapse-hide
# Or we could apply basic math functions [sin, cos] to arrays.
sine_array = np.sin(array_a)
cos_array = np.cos(array_a)
print(sine_array, '\n', cos_array)

[0.84147098 0.90929743 0.14112001] 
 [ 0.54030231 -0.41614684 -0.9899925 ]


## Indexing, Slicing and Iterating

Accessing element in `ndArray` is just better than in `List`.
We could access one element by its *Index*:
```python
element = array[0]
```
or in range, *Slicing*
```python
element = array[0:5]
```
![](animations/index_animation.gif)

## Array Manipulation

We could manipulate shape of array in numpy.
![](animations/stacking_animation.gif)

## Ordering

Sort or find the **Max**, **Min** value in the array.
![](animations/min_max_animation.gif)

<a id=stat></a>
## Basic Statistics

Numpy is originally designed for Data Science, so, it normally have most of the statictics calculations.<br>We could find the basic statistics value `Mean` with `np.mean()`, `Standard Deviation` with `np.std()` and `Variance` with `np.var()` in the array.

## Simple Comparison

The Strength of `Numpy` is its **Broadcasting**, which make calculation much, much faster than `List`.<br>
`List` have to iterate through each and every element to access them, while `Numpy` can iteration one time and get access to all elements.

### Code Complexity

```python
# Add 1: to list
for i in range(len(list_obj)):
    for j in range(len(list_obj[0])):
        for k in range(len(list_obj[0][0])):
            list_obj[i][j][k] += 1
            
# Add 1: to Array
np_array += 1
```

### Speed

We test a function, same input for both `List` and `Numpy Array`, but get different result time.<br>
See more detail in [code](link to code).
Every time you run, the value might be a little different, but:
![](images/run_test.png)

In array, it only costs `4.61ms` when in list it costs `186ms`.<br>
That is so much faster in numpy.

# Matplotlib

Matplotlib is a comprehensive library for creating static, animated, and interactive visualizations in Python.

matplotlib - https://matplotlib.org/

matplotlib.pyplot - https://matplotlib.org/api/pyplot_api.html

### 1. Simple Plots

https://matplotlib.org/3.3.3/api/_as_gen/matplotlib.pyplot.plot.html

### 2. Using Subplots

https://matplotlib.org/3.3.3/api/_as_gen/matplotlib.pyplot.subplots.html

### 3. Scatter plots

https://matplotlib.org/3.3.3/api/_as_gen/matplotlib.pyplot.scatter.html

### 4. Histograms

https://matplotlib.org/3.3.3/api/_as_gen/matplotlib.pyplot.hist.html

# OpenCV

OpenCV (Open Source Computer Vision Library: http://opencv.org) is an open-source library that includes several hundreds of computer vision algorithms.

https://docs.opencv.org/master/index.html

### 1. Reading & Writing Images

##### Basic Functions

cv2.imread(path,flag)

cv2.imshow('title',image)


cv2.waitKey(sec)

cv2.destroyAllWindows()

cv2.imwrite('filename',image)

source - https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_gui/py_image_display/py_image_display.html

### 2. Drawing shapes

cv2.line(image, start_point, end_point, color, thickness)

cv2.cvtColor(src,method)

cv2.rectangle(image, start_point, end_point, color, thickness)

cv2.circle(image, center_coordinates, radius, color, thickness)

cv2.putText(image, text, org, font, fontScale, color[, thickness[, lineType[, bottomLeftOrigin]]])

sources -

https://www.geeksforgeeks.org/

https://docs.opencv.org/master/d6/d6e/group__imgproc__draw.html

### 3. Face Detection with HaarCascade Detector

 cv2.CascadeClassifier(filename)

cv2.CascadeClassifier.detectMultiScale(	image,objects,scaleFactor,minNeighbors,flags,minSize,maxSize)

https://docs.opencv.org/3.4/d1/de5/classcv_1_1CascadeClassifier.html

https://docs.opencv.org/3.4/db/d28/tutorial_cascade_classifier.html

### 4. Resizing images

cv2.resize(input,(size_x,size_y),fx,fy,interpolation)

https://docs.opencv.org/master/da/d6e/tutorial_py_geometric_transformations.html

### 5. Splitting & Merging images

b,g,r = cv2.split(color_image)

image = cv2.merge((r,g,b))

https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_core/py_basic_ops/py_basic_ops.html

### 6. Image translation & rotation

cv2.warpAffine(image, M, output_size, flags, borderMode, borderValue)

cv2.getRotationMatrix2D(center, angle, scale)

https://docs.opencv.org/3.4/d4/d61/tutorial_warp_affine.html

https://www.programcreek.com/python/example/89459/cv2.getRotationMatrix2D

https://docs.opencv.org/3.4/da/d54/group__imgproc__transform.html